### ISSUE TITLE
小白求问，3点疑惑

### ISSUE THREAD

**Issue by moses1994** [ypwhs/captcha_break#12]
您好，我看到您了程序，有3点疑惑：
1）由于我们使用的是循环神经网络，所以默认丢掉前面两个输出，因为它们通常无意义，且会影响模型的输出。
请问这是为什么啊？还有，“前面两个输出”指的是什么？

2） “y_pred 是模型的输出，是按顺序输出的37个字符的概率，因为我们这里用到了循环神经网络，所以需要一个空白字符的概念；”， 为什么“用到了循环神经网络，所以需要一个空白字符的概念”？

3）如果是实际中一段的语音，比如 0.2s---1.8s 是“哦”， 3.4s----6.4s是“嗨”， 这样的事件，该如何制作相应的标签？

希望您可以留下邮箱或者QQ微信，希望可以得到您的回复。

**Comment by ypwhs** [comment]
1. 字面意思，输出指的是循环神经网络的输出。
2. 用循环神经网络没有必要的原因，用 CNN 也可以。如果没有空白字符的概念。就无法区分 a 与 aa。a 循环神经网络会输出 ----aaa---，而 aa 会输出 ---aa--a---
2. label 可以定义为 哦嗨。
