### ISSUE TITLE
请问，如果验证码长度不是4个，而是变化的，在设计模型的时候应该怎么做？

### ISSUE THREAD

**Issue by sisyphusking** [ypwhs/captcha_break#13]
y = [np.zeros((batch_size, n_class), dtype=np.uint8) for i in range(n_len)]  这里应该怎么修改呢

**Comment by ypwhs** [comment]
那你就需要 ctc 了，参考：https://github.com/ypwhs/captcha_break/blob/master/ctc.ipynb
