### ISSUE TITLE
about y_pred[:, 2:, :]

### ISSUE THREAD

**Issue by RenXiandong888** [ypwhs/captcha_break#19]
def ctc_lambda_func(args):
    y_pred, labels, input_length, label_length = args
    y_pred = y_pred[:, 2:, :]
    return K.ctc_batch_cost(labels, y_pred, input_length, label_length)

Can any one explain the mean of y_pred[:, 2:, :]?
Does this "2" have any particular mean？
Thanks a lot.

**Comment by ypwhs** [comment]
2019年更新的代码去掉了这个裁剪的操作，实际上不需要裁剪就可以训练出来好用的模型，之前学得不好，给大家造成了误解，在这里表示抱歉。
