### ISSUE TITLE
你好，能提供下cnn训练出来的模型文件吗

### ISSUE THREAD

**Issue by gantoday** [ypwhs/captcha_break#2]
仓库里只有ctc的模型，没找到cnn的。
可以的话麻烦提供下，谢谢。

**Comment by ypwhs** [comment]
自己训练

发自我的 iPhone

**Comment by gantoday** [comment]
因为在我的电脑训练估计时间是8小时，就想偷个懒。
我晚上开着训练好了。
谢谢你的教程。
