### ISSUE TITLE
你好, 关于旋转图片的疑问

### ISSUE THREAD

**Issue by Zonzely** [ypwhs/captcha_break#20]
加了ctc_loss gru后, 为啥输入的图片需要旋转, 而水平输入到gru呢?

**Comment by ypwhs** [comment]
2019 年更新的代码已经不需要旋转图片了，新的 API 方法是这样的：

```py
x = Permute((2, 1, 3))(x)
x = TimeDistributed(Flatten())(x)
```

先调整轴的顺序，原本是 `(height, width, channels)`，调整为了 `(width, height, channels)`，然后对后面维度进行 Flatten，得到 `(width, height * channels)`，之后就可以用 RNN 在width 这个维度上进行建模了。

**Comment by Zonzely** [comment]
非常感谢
