### ISSUE TITLE
InvalidArgumentError (see above for traceback): Saw a non-null label (index >= num_classes - 1) following a null label, batch: 75 num_classes: 36 labels: [[Node: ctc/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](ctc/Log/_97, ctc/ToInt64/_99, ctc/ToInt32_2/_101, ctc/ToInt32_1/_103)]]

### ISSUE THREAD

**Issue by lxj0276** [ypwhs/captcha_break#8]
我现在把需要训练的图片存入到samples文件下，比如:AB67HG.jpeg,然后我读入数据
rnn_size = 128

characters = string.digits + string.ascii_uppercase

width,height,n_len,n_class= 140,44,6,len(characters)
folder = "sample"
imageList = os.listdir(folder)
imageList = [os.path.join(folder,item) for item in imageList if os.path.isfile(os.path.join(folder,item))]
image_size = len(imageList)

image_array = np.zeros((image_size,height,width,3),dtype=np.uint8)
image_names = []

for i in range(image_size):
img = Image.open(imageList[i])
image_array [i]=img
image_names.append(imageList[i][-11:-5].upper()

# 产生数据
def gen(batch_size=128):
X = np.zeros((batch_size, width, height, 3), dtype=np.uint8)
y = np.zeros((batch_size, n_len), dtype=np.uint8)
while True:
for i in range(batch_size):
num = random.randint(0, image_size - 1)
random_str = image_names[num]
X[i] = np.array(image_array[num]).transpose(1, 0, 2)
y[i] = [characters.find(x) for x in random_str]
yield [X, y, np.ones(batch_size) * int(conv_shape[1] - 2), np.ones(batch_size) * n_len], np.ones(batch_size)

显示这个错误，
InvalidArgumentError (see above for traceback): Saw a non-null label (index >= num_classes - 1) following a null label, batch: 75 num_classes: 36 labels:
[[Node: ctc/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](ctc/Log/_97, ctc/ToInt64/_99, ctc/ToInt32_2/_101, ctc/ToInt32_1/_103)]]
我使用的keras是2.0.3，tensorflow-gpu(1.2.1),用cpu可以运行，但是gpu出问题

**Comment by ypwhs** [comment]
cpu 没问题你就用 cpu 咯。。

**Comment by lxj0276** [comment]
cpu太慢了。。。

**Comment by ypwhs** [comment]
既然 CPU 跑没问题，那八成是 GPU 的版本的问题咯，你试试升级一下 tensorflow-gpu，CUDA 啥的呢
