### ISSUE TITLE
图片切割

### ISSUE THREAD

**Issue by drdeng** [ypwhs/captcha_break#9]
这个不需要对图片中字符进行字符切割吗？captcha 验证码

**Comment by ypwhs** [comment]
是的，不需要，这是一个端到端的深度学习方法

**Comment by drdeng** [comment]
所以这个应该不能去直接识别网站上面的验证码吧，只是一种学习的理想模型

**Comment by drdeng** [comment]
我看了一下网站验证码方面的论文  发现难点都在图片的干扰线 噪声 的去除 以及粘连字符的分割

**Comment by ypwhs** [comment]
能，只要你准备十万样本就好，不需要任何特征工程，你说的处理技术是上个时代的东西了。

你可以认真阅读文章，遇到不会的词就搜一下概念

**Comment by drdeng** [comment]
谢谢您的回答 ， 所以你的意思应该是把上面多个字符当成一个整体作为label吗？ 比如验证码图片上面是5733, 训练的label就是5733

**Comment by ypwhs** [comment]
是的，你可以去查一下端到端(end to end)的定义，我相信你能够理解它的概念
